### PR TITLE
Adding github actions

### PR DESCRIPTION
**Pull request by mhesselbarth**

### CODE REVIEW

**Comment by mhesselbarth** [comment]
Related to #38

**Comment by bitbacchus** [comment]
Thanks a lot @mhesselbarth! This means, we don't use/need tic anymore? Or do you prefer tic @marcosci? (which seems to be kinda cool, btw.)

**Comment by mhesselbarth** [comment]
I delete the tic.R script because I don't think we need it anymore? I never really understood the advantage of it?

**Comment by bitbacchus** [comment]
I agree. AFAIK the advantage is that one can configure it once and run it on multiple CI. But GH actions is so flexible, that this is only useful for more complex projects... Shall I pull?

**Comment by mhesselbarth** [comment]
From my side yes

**Pull request merged**
