### PR TITLE
Bugfix#26

### LINKED ISSUE #26: Wrong result while using weighting in the util_classify function
I am unsure if this is a bug or just my expectations about this function are wrong. I want to classify the `r` raster into two classes having the same number of pixels. However, the result has more pixels of the second class (see a reprex below).

If it is a bug, I think it is inside of the `util_calc_boundaries()` function...

``` r
library(raster)
#> Loading required package: sp
library(NLMR)
library(landscapetools)

set.seed(2020-01-25)
r = nlm_planargradient(100, 100, direction = 90)
r2 = util_classify(r, weighting = c(0.5, 0.5))

freq(r2)
#>      value count
#> [1,]     1  4941
#> [2,]     2  5059

plot(r)
```

``` r
plot(r2)
```

<sup>Created on 2020-01-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                          
#>  version  R version 3.6.2 (2019-12-12)   
#>  os       Fedora 31 (Workstation Edition)
#>  system   x86_64, linux-gnu              
#>  ui       X11                            
#>  language (EN)                           
#>  collate  en_US.UTF-8                    
#>  ctype    en_US.UTF-8                    
#>  tz       Europe/Warsaw                  
#>  date     2020-01-25                     
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package        * version    date       lib source                          
#>  assertthat       0.2.1      2019-03-21 [1] CRAN (R 3.6.0)                  
#>  backports        1.1.5      2019-10-02 [1] CRAN (R 3.6.1)                  
#>  callr            3.4.0      2019-12-09 [1] CRAN (R 3.6.2)                  
#>  checkmate        1.9.4      2019-07-04 [1] CRAN (R 3.6.0)                  
#>  cli              2.0.1      2020-01-08 [1] CRAN (R 3.6.2)                  
#>  codetools        0.2-16     2018-12-24 [2] CRAN (R 3.6.2)                  
#>  crayon           1.3.4      2017-09-16 [1] CRAN (R 3.6.0)                  
#>  curl             4.3        2019-12-02 [1] CRAN (R 3.6.2)                  
#>  desc             1.2.0      2018-05-01 [1] CRAN (R 3.6.0)                  
#>  devtools         2.2.1      2019-09-24 [1] CRAN (R 3.6.1)                  
#>  digest           0.6.23     2019-11-23 [1] CRAN (R 3.6.1)                  
#>  ellipsis         0.3.0      2019-09-20 [1] CRAN (R 3.6.1)                  
#>  evaluate         0.14       2019-05-28 [1] CRAN (R 3.6.0)                  
#>  fansi            0.4.1      2020-01-08 [1] CRAN (R 3.6.2)                  
#>  fs               1.3.1      2019-05-06 [1] CRAN (R 3.6.0)                  
#>  glue             1.3.1      2019-03-12 [1] CRAN (R 3.6.0)                  
#>  highr            0.8        2019-03-20 [1] CRAN (R 3.6.0)                  
#>  htmltools        0.4.0      2019-10-04 [1] CRAN (R 3.6.1)                  
#>  httr             1.4.1      2019-08-05 [1] CRAN (R 3.6.0)                  
#>  knitr            1.27       2020-01-16 [1] CRAN (R 3.6.2)                  
#>  landscapetools * 0.6.0      2019-11-14 [1] local                           
#>  lattice          0.20-38    2018-11-04 [2] CRAN (R 3.6.2)                  
#>  magrittr         1.5        2014-11-22 [1] CRAN (R 3.6.0)                  
#>  memoise          1.1.0      2017-04-21 [1] CRAN (R 3.6.0)                  
#>  mime             0.8        2019-12-19 [1] CRAN (R 3.6.2)                  
#>  NLMR           * 1.0        2020-01-23 [1] CRAN (R 3.6.2)                  
#>  pkgbuild         1.0.6      2019-10-09 [1] CRAN (R 3.6.1)                  
#>  pkgload          1.0.2      2018-10-29 [1] CRAN (R 3.6.0)                  
#>  prettyunits      1.1.0      2020-01-09 [1] CRAN (R 3.6.2)                  
#>  processx         3.4.1      2019-07-18 [1] CRAN (R 3.6.0)                  
#>  ps               1.3.0      2018-12-21 [1] CRAN (R 3.6.0)                  
#>  R6               2.4.1      2019-11-12 [1] CRAN (R 3.6.1)                  
#>  raster         * 3.0-11     2020-01-19 [1] Github (rspatial/raster@4988ed0)
#>  Rcpp             1.0.3      2019-11-08 [1] CRAN (R 3.6.1)                  
#>  remotes          2.1.0      2019-06-24 [1] CRAN (R 3.6.0)                  
#>  rlang            0.4.2.9001 2020-01-19 [1] Github (r-lib/rlang@cdf1391)    
#>  rmarkdown        2.0        2019-12-12 [1] CRAN (R 3.6.2)                  
#>  rprojroot        1.3-2      2018-01-03 [1] CRAN (R 3.6.0)                  
#>  sessioninfo      1.1.1      2018-11-05 [1] CRAN (R 3.6.0)                  
#>  sp             * 1.3-2      2019-11-07 [1] CRAN (R 3.6.1)                  
#>  stringi          1.4.5      2020-01-11 [1] CRAN (R 3.6.2)                  
#>  stringr          1.4.0      2019-02-10 [1] CRAN (R 3.6.1)                  
#>  testthat         2.3.1      2019-12-01 [1] CRAN (R 3.6.2)                  
#>  usethis          1.5.1      2019-07-04 [1] CRAN (R 3.6.0)                  
#>  withr            2.1.2      2018-03-15 [1] CRAN (R 3.6.0)                  
#>  xfun             0.12       2020-01-13 [1] CRAN (R 3.6.2)                  
#>  xml2             1.2.2      2019-08-09 [1] CRAN (R 3.6.0)                  
#>  yaml             2.2.0      2018-07-25 [1] CRAN (R 3.6.0)                  
#> 
#> [1] /home/jn/R/x86_64-redhat-linux-gnu-library/3.6
#> [2] /usr/lib64/R/library
#> [3] /usr/share/R/library
```

</details>

### PR DESCRIPTION
**Pull request by bitbacchus**
This aims to fix #26. I changed the following part in `util_classify.R` 
## New:
```
.classify <- function(x, weighting){
#[...]
  # Classify the matrix based on the boundary values ----
  raster::values(x) <-  base::cut(raster::values(x),
                                  breaks = c(0, boundary_values),
                                  include.lowest = TRUE, labels = FALSE)

#[...]
}
```
## Old
```
.classify <- function(x, weighting){
#[...]
# Classify the matrix based on the boundary values ----
  raster::values(x) <- findInterval(raster::values(x),
                                    boundary_values,
                                    rightmost.closed = TRUE)

  # first class should be 1
  x <- x + 1

#[...]
}
```

Does anyone see something that could go wrong with the new version?

Besides, we should write a test that covers issue #26 before merging.

### CODE REVIEW

**Comment by Nowosad** [comment]
It works well in several examples I have checked. @mhesselbarth? @marcosci?

Btw @bitbacchus - I think you also should update the package version.

**Comment by mhesselbarth** [comment]
I think this slightly changes the usage for the user. With the old example, the users could specify the intervals, now the breaks must be specified. Not saying I don't like the new version, though.

**Comment by Nowosad** [comment]
@mhesselbarth could the users do that? Are you sure or am I missing something? `.classify()` is an internal function, with minimal user control:

https://github.com/ropensci/landscapetools/blob/ec752ccc9af58a7fca067cc7ec45d31d18723b9f/R/util_classify.R#L125-L148

**Comment by mhesselbarth** [comment]
Yeah my bad...I was talking bullshit, sorry.

**Pull request merged**
